version: '3.8'

services:
  web:
    build: 
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - ENV=development
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - .:/app
      - /app/__pycache__

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"